---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus-exporter-weather
  labels:
    app.kubernetes.io/name: prometheus-exporter-weather
spec:
  containers:
  - name: prometheus-exporter-weather
    image: ghcr.io/josephchapman/prometheus-exporter-weather:master
    envFrom:
    - configMapRef:
        name: locations-env
    resources:
      limits:
        memory: "32Mi"
        cpu: "50m"
    ports:
    - containerPort: 2112
