---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-exporter-weather
spec:
  selector:
    app.kubernetes.io/name: prometheus-exporter-weather
  ports:
    - protocol: TCP
      port: 2112
      targetPort: 2112