[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = true

[[inputs.http]]
  urls = ["${UTILITIES}"]
  data_format = "csv"
  tagexclude = ["url"]
  name_override = "utilities"
  csv_skip_rows = 5
  csv_column_names = ["time", "source", "water_import", "electricity_import", "electricity_export", "electricity_generation", "electricity_consumption"]
  csv_column_types = ["string", "string", "float", "float", "float", "float", "float"]
  csv_timestamp_column = "time"
  csv_timestamp_format = "2006-01-02 15:04"
  csv_tag_columns = ["source"]
  interval = "240m"

[[inputs.http]]
  urls = ["${COMPOSITION}"]
  data_format = "csv"
  tagexclude = ["url"]
  name_override = "composition"
  csv_skip_rows = 1
  csv_column_names = ["date", "weight", "fat_percent", "fat_mass", "soft_lean_mass", "fat_free_mass", "ffmi", "bmi", "bmr", "waist", "pb_squat", "pb_bench", "pb_deadlift"]
  csv_column_types = ["string", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]
  csv_timestamp_column = "date"
  csv_timestamp_format = "2006-01-02"
  interval = "240m"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"

