receivers:
  fluent_forward:
    endpoint: 0.0.0.0:24224
exporters:
  debug:
    verbosity: detailed
  otlp_http:
    endpoint: http://loki:3100/otlp
service:
  pipelines:
    logs:
      receivers:
        - fluent_forward
      exporters:
        - otlp_http
