apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  uid: "ERgg9hAnMdw4Lpf9"
  # isDefault: true
  # access: proxy
  # editable: true
- name: Loki
  type: loki
  url: http://loki:3100
  uid: "ew4xLMxwfh3Yq3iA"
  # basicAuth: false
  # isDefault: false
  # editable: false
- name: InfluxDB
  type: influxdb
  url: http://influxdb:8086
  uid: "qEKFKeXVHztEvAw7"
  jsonData:
    dbName: "my-bucket"
    defaultBucket: "my-bucket"
    httpMode: "POST"
    organization: "my-org"
    version: "Flux"
  secureJsonData:
    token: my-super-secret-auth-token
  editable: true