receivers:
 fluentforward:
   endpoint: 0.0.0.0:24224
exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: http://loki:3100/otlp
service:
  pipelines:
    logs:
      receivers:
        - fluentforward
      exporters:
        - otlphttp
