[[inputs.http]]
  urls = ["${COMPOSITION}"]
  data_format = "csv"
  tagexclude = ["url", "comment"]
  name_override = "composition"
  csv_skip_rows = 1
  csv_column_names = ["date", "weight", "fat_percent", "soft_lean_mass", "waist", "pb_squat", "pb_bench", "pb_deadlift", "comment", "fat_mass", "fat_free_mass", "ffmi", "bmi", "bmr"]
  csv_column_types = ["string", "float", "float", "float", "float", "float", "float", "float", "string", "float", "float", "float", "float", "float"]
  csv_timestamp_column = "date"
  csv_timestamp_format = "2006-01-02"
  interval = "4h"