[[inputs.http]]
  alias = "prediction"
  urls = [
    "https://gamma-api.polymarket.com/markets/${MARKET1}"
  ]
  interval = "1h"
  timeout = "10s"
  method = "GET"

  data_format = "json_v2"

  [[inputs.http.json_v2]]
    measurement_name = "prediction"

    [[inputs.http.json_v2.field]]
      path = "outcomePrices"
      type = "string"
    
    [[inputs.http.json_v2.tag]]
      path = "id"
    [[inputs.http.json_v2.tag]]
      path = "question"

[[processors.starlark]]
  namepass = ["prediction"]
  source = '''
load("json.star", "json")

def apply(metric):
    raw_prices = metric.fields.get("outcomePrices")
    if raw_prices:
        prices_array = json.decode(raw_prices)
        if len(prices_array) > 0:
            metric.fields["yes"] = float(prices_array[0])

    metric.fields.pop("outcomePrices", None)

    return metric
'''
