[[inputs.http]]
  urls = [
    "https://gamma-api.polymarket.com/events/slug/${EVENT_SLUG_1}"
  ]
  interval = "1h"
  timeout = "10s"
  method = "GET"
  name_override = "${TEAM_NICK}"
  tagexclude = ["url"]
  data_format = "json_v2"

  [[inputs.http.json_v2]]
    [[inputs.http.json_v2.tag]]
      path = "eventDate"
    [[inputs.http.json_v2.tag]]
      path = "sport.name"
      rename = "league"

    [[inputs.http.json_v2.field]]
      path = "markets.#(groupItemTitle==${TEAM_LONG}).lastTradePrice"
      rename = "win"
      type = "float"