[[inputs.http]]
  urls = ["${UTILITIES}"]
  data_format = "csv"
  tagexclude = ["url"]
  name_override = "utilities"
  csv_skip_rows = 1
  csv_column_names = ["time", "source", "water_import", "electricity_import", "electricity_export", "electricity_generation", "invoice", "water_consumption_bill", "electricity_consumption_bill", "electricity_generation_bill", "comment", "electricity_consumption"]
  csv_column_types = ["string", "string", "float", "float", "float", "float", "float", "float", "float", "float", "string", "float"]
  csv_timestamp_column = "time"
  csv_timestamp_format = "2006-01-02 15:04"
  csv_tag_columns = ["source"]
  interval = "4h"