{
 "title": "Speedrun",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "OoT Defeat Ganon (Time)",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"The Legend of Zelda: Ocarina of Time\" | current_record_category=\"Defeat Ganon\" | line_format \"{{.current_record_time}}\""
    }
   ]
  },
  {
   "title": "OoT Defeat Ganon (Player)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"The Legend of Zelda: Ocarina of Time\" | current_record_category=\"Defeat Ganon\" | line_format \"{{.current_record_player}}\""
    }
   ]
  },
  {
   "title": "OoT Defeat Ganon (Days ago)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"The Legend of Zelda: Ocarina of Time\" | current_record_category=\"Defeat Ganon\" | line_format \"{{.current_record_performed_days_ago}}\""
    }
   ]
  },
  {
   "title": "WWHD Any% (Time)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"The Legend of Zelda: The Wind Waker HD\" | current_record_category=\"Any%\" | line_format \"{{.current_record_time}}\""
    }
   ]
  },
  {
   "title": "WWHD Any% (Player)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"The Legend of Zelda: The Wind Waker HD\" | current_record_category=\"Any%\" | line_format \"{{.current_record_player}}\""
    }
   ]
  },
  {
   "title": "WWHD Any% (Days ago)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"The Legend of Zelda: The Wind Waker HD\" | current_record_category=\"Any%\" | line_format \"{{.current_record_performed_days_ago}}\""
    }
   ]
  },
  {
   "title": "SM64 120 Star (Time)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"Super Mario 64\" | current_record_category=\"120 Star\" | line_format \"{{.current_record_time}}\""
    }
   ]
  },
  {
   "title": "SM64 120 Star (Player)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"Super Mario 64\" | current_record_category=\"120 Star\" | line_format \"{{.current_record_player}}\""
    }
   ]
  },
  {
   "title": "SM64 120 Star (Days ago)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"Super Mario 64\" | current_record_category=\"120 Star\" | line_format \"{{.current_record_performed_days_ago}}\""
    }
   ]
  },
  {
   "title": "SM64 70 Star (Time)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"Super Mario 64\" | current_record_category=\"70 Star\" | line_format \"{{.current_record_time}}\""
    }
   ]
  },
  {
   "title": "SM64 70 Star (Player)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"Super Mario 64\" | current_record_category=\"70 Star\" | line_format \"{{.current_record_player}}\""
    }
   ]
  },
  {
   "title": "SM64 70 Star (Days ago)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"unknown_service\"} | json | application=\"logger-speedrun\" | current_record_game=\"Super Mario 64\" | current_record_category=\"70 Star\" | line_format \"{{.current_record_performed_days_ago}}\""
    }
   ]
  }
 ]
}