# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  test-prometheus-exporter-weather:
    name: Test prometheus-exporter-weather
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
      
      - name: Install dependencies
        run: go get -C prometheus-exporter-weather/src .

      - name: Test
        run: go test -C prometheus-exporter-weather/src -v ./...

  build-prometheus-exporter-weather:
    name: Build prometheus-exporter-weather
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
      
      - name: Install dependencies
        run: go get -C prometheus-exporter-weather/src .

      - name: Build
        run: go build -C prometheus-exporter-weather/src -v ./...
