---
name: prometheus-exporter-weather

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  test-prometheus-exporter-weather:
    name: Test prometheus-exporter-weather
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
      
      - name: Install dependencies
        run: go get -C prometheus-exporter-weather/src .

      - name: Test
        run: go test -C prometheus-exporter-weather/src -v ./...

  build-prometheus-exporter-weather:
    name: Build prometheus-exporter-weather
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
      
      - name: Install dependencies
        run: go get -C prometheus-exporter-weather/src .

      - name: Build
        run: go build -C prometheus-exporter-weather/src -v ./...

  build-and-push-prometheus-exporter-weather-image:
    name: Build and push prometheus-exporter-weather container
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: ./prometheus-exporter-weather/Dockerfile
          context: ./prometheus-exporter-weather
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true